language: python
python:
  - "3.7"
#services:
#  - docker
before_script:
  - pip install docker-compose
  - docker-compose build
  - docker-compose up -d
#script: "flask run --host=0.0.0.0 & pytest tests/tests_api/test_todo.py"
script:
  - pytest ./tests/tests_api/test_todo.py