language: python
python:
  - "3.7"
cache: pip
install:
  - "pip3 install -r requirements.txt"
#before_script: flask run --host=0.0.0.0
#script: pytest tests/tests_api/test_todo.py
script: "flask run --host=0.0.0.0 && pytest tests/tests_api/test_todo.py"