language: python

python:
  - "3.7"
sudo: required

services:
  - docker

before_script:
  - pip install docker-compose
  - docker-compose build
  - docker-compose up -d

#script: "flask run --host=0.0.0.0 & pytest tests/tests_api/test_todo.py"
#script: docker-compose up --build -d && pytest
script:
  - sh -c "ls tests/tests_api/"
#  - docker-compose up -d
  - pytest
after_script:
  - docker-compose down