version: "3"
services:
  todo_list_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo
    #command: gunicorn -w 4 --bind 0.0.0.0:5000 run:app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    env_file:
      - .flaskenv
    ports:
      - "5000:5000"
    volumes:
      - ./todo_list_api:/todo_list_api
    depends_on:
      - mongodb
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - "27018:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 20
    ports:
      - "5050:5050"
    volumes:
      - /allure-results:/app/allure-results
      - /allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"

