version: "3"
services:
  todo_list_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: todo
    #command: gunicorn -w 4 --bind 0.0.0.0:5000 run:app
    command: gunicorn --bind 0.0.0.0:5000 run:app
    env_file:
      - .flaskenv
    ports:
      - "5000:5000"
    volumes:
      - ./todo_list_api:/todo_list_api
    depends_on:
      - mongodb
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
    - "27018:27017"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


#DEV_DATABASE_URI='mongodb://localhost:27017/DevTodoDB'
#DEV_REDIS_URI='redis://localhost:6379/0'
#DEV_DOCKER_DATABASE_URI='mongodb://mongodb:27017/DevTodoDB'
#SECRET_KEY='a02c3cf84bc4a66b8a9a13dba5f4516b'
#SECRET_KEY_FOR_ADMIN= "9cc3a144772b168ca171cea9599fa73f"
#JWT_BLACKLIST_ENABLED=True
# .env